//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.28 at 06:15:45 PM EDT 
//


package org.openmrs.module.integration.api.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openmrs.module.integration.api.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openmrs.module.integration.api.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReportTemplates }
     * 
     */
    public ReportTemplates createReportTemplates() {
        return new ReportTemplates();
    }

    /**
     * Create an instance of {@link MetaData }
     * 
     */
    public MetaData createMetaData() {
        return new MetaData();
    }

    /**
     * Create an instance of {@link MetaData.OrganisationUnits }
     * 
     */
    public MetaData.OrganisationUnits createMetaDataOrganisationUnits() {
        return new MetaData.OrganisationUnits();
    }

    /**
     * Create an instance of {@link MetaData.CategoryOptionCombos }
     * 
     */
    public MetaData.CategoryOptionCombos createMetaDataCategoryOptionCombos() {
        return new MetaData.CategoryOptionCombos();
    }

    /**
     * Create an instance of {@link MetaData.CategoryOptionCombos.CategoryOptionCombo }
     * 
     */
    public MetaData.CategoryOptionCombos.CategoryOptionCombo createMetaDataCategoryOptionCombosCategoryOptionCombo() {
        return new MetaData.CategoryOptionCombos.CategoryOptionCombo();
    }

    /**
     * Create an instance of {@link MetaData.CategoryOptionCombos.CategoryOptionCombo.CategoryOptions }
     * 
     */
    public MetaData.CategoryOptionCombos.CategoryOptionCombo.CategoryOptions createMetaDataCategoryOptionCombosCategoryOptionComboCategoryOptions() {
        return new MetaData.CategoryOptionCombos.CategoryOptionCombo.CategoryOptions();
    }

    /**
     * Create an instance of {@link MetaData.Categories }
     * 
     */
    public MetaData.Categories createMetaDataCategories() {
        return new MetaData.Categories();
    }

    /**
     * Create an instance of {@link MetaData.Categories.Category }
     * 
     */
    public MetaData.Categories.Category createMetaDataCategoriesCategory() {
        return new MetaData.Categories.Category();
    }

    /**
     * Create an instance of {@link MetaData.Categories.Category.CategoryOptions }
     * 
     */
    public MetaData.Categories.Category.CategoryOptions createMetaDataCategoriesCategoryCategoryOptions() {
        return new MetaData.Categories.Category.CategoryOptions();
    }

    /**
     * Create an instance of {@link ReportTemplates.ReportTemplate }
     * 
     */
    public ReportTemplates.ReportTemplate createReportTemplatesReportTemplate() {
        return new ReportTemplates.ReportTemplate();
    }

    /**
     * Create an instance of {@link ReportTemplates.ReportTemplate.DataValueTemplates }
     * 
     */
    public ReportTemplates.ReportTemplate.DataValueTemplates createReportTemplatesReportTemplateDataValueTemplates() {
        return new ReportTemplates.ReportTemplate.DataValueTemplates();
    }

    /**
     * Create an instance of {@link ReportTemplates.Disaggregations }
     * 
     */
    public ReportTemplates.Disaggregations createReportTemplatesDisaggregations() {
        return new ReportTemplates.Disaggregations();
    }

    /**
     * Create an instance of {@link ReportTemplates.DataElements }
     * 
     */
    public ReportTemplates.DataElements createReportTemplatesDataElements() {
        return new ReportTemplates.DataElements();
    }

    /**
     * Create an instance of {@link OrgUnitType }
     * 
     */
    public OrgUnitType createOrgUnitType() {
        return new OrgUnitType();
    }

    /**
     * Create an instance of {@link MetaData.OrganisationUnits.OrganisationUnit }
     * 
     */
    public MetaData.OrganisationUnits.OrganisationUnit createMetaDataOrganisationUnitsOrganisationUnit() {
        return new MetaData.OrganisationUnits.OrganisationUnit();
    }

    /**
     * Create an instance of {@link MetaData.CategoryOptionCombos.CategoryOptionCombo.CategoryCombo }
     * 
     */
    public MetaData.CategoryOptionCombos.CategoryOptionCombo.CategoryCombo createMetaDataCategoryOptionCombosCategoryOptionComboCategoryCombo() {
        return new MetaData.CategoryOptionCombos.CategoryOptionCombo.CategoryCombo();
    }

    /**
     * Create an instance of {@link MetaData.CategoryOptionCombos.CategoryOptionCombo.CategoryOptions.CategoryOption }
     * 
     */
    public MetaData.CategoryOptionCombos.CategoryOptionCombo.CategoryOptions.CategoryOption createMetaDataCategoryOptionCombosCategoryOptionComboCategoryOptionsCategoryOption() {
        return new MetaData.CategoryOptionCombos.CategoryOptionCombo.CategoryOptions.CategoryOption();
    }

    /**
     * Create an instance of {@link MetaData.Categories.Category.Concept }
     * 
     */
    public MetaData.Categories.Category.Concept createMetaDataCategoriesCategoryConcept() {
        return new MetaData.Categories.Category.Concept();
    }

    /**
     * Create an instance of {@link MetaData.Categories.Category.CategoryOptions.CategoryOption }
     * 
     */
    public MetaData.Categories.Category.CategoryOptions.CategoryOption createMetaDataCategoriesCategoryCategoryOptionsCategoryOption() {
        return new MetaData.Categories.Category.CategoryOptions.CategoryOption();
    }

    /**
     * Create an instance of {@link ReportTemplates.ReportTemplate.DataValueTemplates.DataValueTemplate }
     * 
     */
    public ReportTemplates.ReportTemplate.DataValueTemplates.DataValueTemplate createReportTemplatesReportTemplateDataValueTemplatesDataValueTemplate() {
        return new ReportTemplates.ReportTemplate.DataValueTemplates.DataValueTemplate();
    }

    /**
     * Create an instance of {@link ReportTemplates.Disaggregations.Disaggregation }
     * 
     */
    public ReportTemplates.Disaggregations.Disaggregation createReportTemplatesDisaggregationsDisaggregation() {
        return new ReportTemplates.Disaggregations.Disaggregation();
    }

    /**
     * Create an instance of {@link ReportTemplates.DataElements.DataElement }
     * 
     */
    public ReportTemplates.DataElements.DataElement createReportTemplatesDataElementsDataElement() {
        return new ReportTemplates.DataElements.DataElement();
    }

}
